/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAuthentification (void);
GtkWidget* create_admin_addEts_achref (void);
GtkWidget* create_Modifier_ETS_achref (void);
GtkWidget* create_DeleteEts_achref (void);
GtkWidget* create_espaceAdmin (void);
GtkWidget* create_Firas_Ajout (void);
GtkWidget* create_Firas_Suppression (void);
GtkWidget* create_Firas_Modifier (void);
GtkWidget* create_Succeed_Supp (void);
GtkWidget* create_Firas_statistic (void);
GtkWidget* create_menu_Firas (void);
